# permissions:
# default permssions >
# autopvpkit.kit = access to '/apk kit' command
# autopvpkit.kits.<name> = access to a kit when you join/respawn/worldchange/worldguard-region-entry
# autopvpkit.savekit = access to '/savekit' command which saves kit item slots to the slots you like them to be placed on when the kit gets selected for you. Also, '/savekit remove'.
# admin permissions >
# autopvpkit.kit.other = access to give other players a kit using '/apk kit <kit> <player>'
# autopvpkit.kits.* = access to all kits
# autopvpkit.admin = access to other admin commands: /apk reload, /apk load, /apk save
Settings:
  change-on-spawn: true
  change-on-respawn: true
  change-on-world-change: true
  disable-kit-drops: false
  disable-kit-drops-on-death: false
  disabled-worlds:
  - "a disabled world"
  kit-does-not-exist: "&7The kit &c%kit% &7doesn't exist."
  kit-no-permission: "&7Sorry, but you don't have permission to use this kit."
  player-does-not-exist: "&7Unable to find player: &c%player%&7."
  kit-other-no-permission: "&cYou don't have permission to give kit to other players."
  # placeholders: %kit%
  kit-save: "&7Your current kit has been saved with this inventory."
  kit-save-no-selected-kit: "&7You don't have any kit selected!"
  kit-save-removed: "&7Removed the saved slots of your current kit."
  kit-save-no-permission: "&7Sorry, but you don't have permission to save kits."
  # placeholders: %kit% %kit_displayname%
  kit-message: "&7Selected kit: &c%kit%&7."
  kit-message-other: "&7Given kit &c%kit% &7to &c%player%&7."
  # must have WorldEdit and WorldGuard for this to work.
  worldguard-hook: false
WorldGuard-Settings:
  # select a kit when you enter a region?
  change-on-worldguard-region: true
  worldguard-region: "pvp"
Kits:
  member:
    display-name: "&7Default"
    helmet:
      item: IRON_HELMET
      amount: 1
      data: 0
      name: "&eDefault Helmet"
      lore:
      - "&fa lore line"
      enchantments:
      - "protect 1"
    chestplate:
      item: IRON_CHESTPLATE
      amount: 1
      data: 0
    leggings:
      item: IRON_LEGGINGS
      amount: 1
      data: 0
    boots:
      item: IRON_BOOTS
      amount: 1
      data: 0
    0:
      item: STONE_SWORD
      amount: 1
      data: 0
      enchantments:
      - "sharpness 1"
    1:
      item: BOW
      amount: 1
      data: 0
      enchantments:
      - "power 1"
      lore:
      - "&cPower I"
      flags:
      - "HIDE_ENCHANT"
    2:
      item: ARROW
      amount: 2
      data: 0
  vip:
    display-name: "&6Vip"
    helmet:
      item: DIAMOND_HELMET
      amount: 1
      data: 0
    chestplate:
      item: IRON_CHESTPLATE
      amount: 1
      data: 0
    leggings:
      item: IRON_LEGGINGS
      amount: 1
      data: 0
    boots:
      item: IRON_BOOTS
      amount: 1
      data: 0
    0:
      item: IRON_SWORD
      amount: 1
      data: 0
      name: "&6Vip &7Sword"
      enchantments:
      - "sharpness 1"