main: me.autopvpkit.AutoPvPKit
version: 2.3
author: "TheGaming999"
name: "AutoPvPKit-Reborn"
softdepend: [WorldEdit, WorldGuard]
commands:
  autopvpkit:
    usage: /<command>
    description: main command
    aliases: [apk, apkit, apvpkit]
  savekit:
    usage: /<command>
    description: save kit command
    aliases: [savek, skit]